# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box     = "fedora-44-cloud-base"
  config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-VirtualBox-44-1.7.x86_64.vagrant.virtualbox.box"
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "7fb67d4224541a548f4d9622695b245f007a5bdfe608e291860da0d8597ec4b1"

  config.vm.hostname = "vulntrack-dev"
  config.disksize.size = "60GB"

  config.vm.network "private_network", ip: "192.168.56.61"
  config.vm.network "forwarded_port", guest: 8080, host: 8080,  host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5432, host: 15432, host_ip: "127.0.0.1"

  config.ssh.forward_agent = true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "vulntrack-fedora-dev"
    vb.memory = 8192
    vb.cpus   = 4
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", "1"]
  end

  config.vm.provision "shell", path: "provision.sh"
end