apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vulntrack
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /vulntrack/api/ping
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:825990809758:certificate/b79f4f95-d533-42e9-9528-7ff03d142ebc
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: aws.vulntrack.app
spec:
  ingressClassName: alb
  rules:
    - host: aws.vulntrack.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80
